name: BetterTeamsAddon
version: '1.2.0'
depend: [BetterTeams, PlaceholderAPI]
author: bedike16
main: hu.bedike16.betterteamsaddon.Main
website: http://donate.bedike16.hu/
api-version: '1.12'

commands:
  betterteamsaddon:
    aliases: [ bta, teamsaddon ]
  teamleaderboard:
    aliases: [ teamboard, tleaderboard ]